volumes:
  kancraonewms_local_postgres_data: {}
  kancraonewms_local_postgres_data_backups: {}
  kancraonewms_local_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: kancraonewms_local_django
    container_name: kancraonewms_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: kancraonewms_production_postgres
    container_name: kancraonewms_local_postgres
    volumes:
      - kancraonewms_local_postgres_data:/var/lib/postgresql/18/docker
      - kancraonewms_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: kancraonewms_local_mailpit
    ports:
      - '8025:8025'

  redis:
    image: docker.io/redis:8.6
    container_name: kancraonewms_local_redis
    volumes:
      - kancraonewms_local_redis_data:/data

  celeryworker:
    <<: *django
    image: kancraonewms_local_celeryworker
    container_name: kancraonewms_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: kancraonewms_local_celerybeat
    container_name: kancraonewms_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: kancraonewms_local_flower
    container_name: kancraonewms_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: kancraonewms_local_node
    container_name: kancraonewms_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
